const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('clipforge', {
  init: () => ipcRenderer.invoke('app:init'),
  saveSettings: (settings) => ipcRenderer.invoke('settings:save', settings),
  getCaptureSource: () => ipcRenderer.invoke('capture:get-source'),
  listClips: () => ipcRenderer.invoke('clips:list'),
  listScreenshots: () => ipcRenderer.invoke('screenshots:list'),
  saveClip: (payload) => ipcRenderer.invoke('clip:save', payload),
  trimClip: (payload) => ipcRenderer.invoke('clip:trim', payload),
  renameClip: (payload) => ipcRenderer.invoke('clip:rename', payload),
  stripAudio: (payload) => ipcRenderer.invoke('clip:strip-audio', payload),
  revealClip: (clipPath) => ipcRenderer.invoke('clip:reveal', clipPath),
  revealScreenshot: (shotPath) => ipcRenderer.invoke('screenshot:reveal', shotPath),
  deleteScreenshot: (shotPath) => ipcRenderer.invoke('screenshot:delete', shotPath),
  renameScreenshot: (payload) => ipcRenderer.invoke('screenshot:rename', payload),
  saveEditedScreenshot: (payload) => ipcRenderer.invoke('screenshot:save-edited', payload),
  listAudioApps: () => ipcRenderer.invoke('audio:list-apps'),
  listNotificationSounds: () => ipcRenderer.invoke('sound:list'),
  addNotificationSound: () => ipcRenderer.invoke('sound:add'),
  selectNotificationSound: (id) => ipcRenderer.invoke('sound:select', id),
  deleteNotificationSound: (id) => ipcRenderer.invoke('sound:delete', id),
  resetBuffer: () => ipcRenderer.invoke('buffer:reset'),
  writeBufferChunk: (payload) => ipcRenderer.invoke('buffer:chunk', payload),
  saveBufferedClip: (payload) => ipcRenderer.invoke('buffer:save-clip', payload),
  startGpuCapture: (payload) => ipcRenderer.invoke('gpu:start', payload),
  stopGpuCapture: () => ipcRenderer.invoke('gpu:stop'),
  saveGpuClip: (payload) => ipcRenderer.invoke('gpu:save-clip', payload),
  deleteClip: (clipPath) => ipcRenderer.invoke('clip:delete', clipPath),
  minimize: () => ipcRenderer.invoke('window:minimize'),
  hide: () => ipcRenderer.invoke('window:hide'),
  show: () => ipcRenderer.invoke('window:show'),
  toggleMaximize: () => ipcRenderer.invoke('window:toggle-maximize'),
  debugLog: (message, extra) => ipcRenderer.invoke('debug:log', { message, extra }),
  onSaveClip: (callback) => ipcRenderer.on('save-clip', callback),
  onScreenshotSaved: (callback) => ipcRenderer.on('screenshot-saved', (_event, value) => callback(value)),
  onHotkeyStatus: (callback) => ipcRenderer.on('hotkey-status', (_event, value) => callback(value)),
  onGpuStatus: (callback) => ipcRenderer.on('gpu-status', (_event, value) => callback(value)),
  onUpdateStatus: (callback) => ipcRenderer.on('update-status', (_event, value) => callback(value))
});
